import os

GOOGLE_CREDENTIALS = os.getenv("GOOGLE_CREDENTIALS_PATH")  # Path to Google Cloud JSON key
OPENAI_API_KEY = os.getenv("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")
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")